# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        resolve_target_entities:
            Acme\Domain\Blog\Model\Author:   Acme\Infrastructure\Bundle\AppBundle\Entity\AuthorEntity
            Acme\Domain\Blog\Model\Category: Acme\Infrastructure\Bundle\AppBundle\Entity\CategoryEntity
            Acme\Domain\Blog\Model\Comment:  Acme\Infrastructure\Bundle\AppBundle\Entity\CommentEntity
            Acme\Domain\Blog\Model\Post:     Acme\Infrastructure\Bundle\AppBundle\Entity\PostEntity
            Acme\Domain\Blog\Model\Tag:      Acme\Infrastructure\Bundle\AppBundle\Entity\TagEntity
