language: php

php:
  - 7.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer selfupdate
  - composer require --global phpunit/phpunit

install: composer install --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - ~/.composer/vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=coverage.clover

notifications:
  email: yann.eugone@gmail.com
