language: php

php:
  - 7.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer selfupdate

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=coverage.clover

notifications:
  email: yann.eugone@gmail.com
