language: php

php:
  - 7.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer selfupdate
  - composer global require phpunit/phpunit

install: composer install --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - ~/.composer/vendor/bin/phpunit -c phpunit.xml.dist --coverage-text --coverage-clover=clover.coverage

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.coverage

notifications:
  email: yann.eugone@gmail.com
