version: '2'

services:

  apache:
    container_name: workshop-hexagonal-apache
    image: gitlab.prestaconcept.net:7443/docker/apache-php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/src
    working_dir: /src
    hostname: apache
    links:
      - mysql:mysql
    extends:
        file: ~/.led/docker-base.yaml
        service: localuser

  mysql:
    container_name: workshop-hexagonal-mysql
    image: gitlab.prestaconcept.net:7443/docker/mysql
    ports:
      - "3306:3306"
    hostname: mysql
    volumes:
      - ./var/mysql:/home/data
    extends:
        file: ~/.led/docker-base.yaml
        service: localuser

  maildev:
    container_name: workshop-hexagonal-maildev
    image: gitlab.prestaconcept.net:7443/docker/maildev
    hostname: maildev
    ports:
      - "1080:80"
