imports:
    - { resource: parameters-default.yml }
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: framework/ }
    - { resource: bundles/ }
    - { resource: services/ }
