security:

    encoders:
        Symfony\Component\Security\Core\User\UserInterface: bcrypt

    providers:
        main:
            entity:
                class:    Acme\Infrastructure\Bundle\AppBundle\Entity\Author
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:   ^/
            anonymous: true
            provider:  main
            form_login:
                login_path:         security_login
                check_path:         security_authenticate
                username_parameter: username
                password_parameter: password
            logout:
                path:   security_logout
                target: security_login
            remember_me:
                secret:                "%secret%"
                lifetime:              31536000 # 365 days
                path:                  /
                domain:                ~
                remember_me_parameter: remember

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,       roles: IS_AUTHENTICATED_REMEMBERED }
